### ISSUE TITLE
kf5-sonnet fails to build

### ISSUE THREAD

**Issue by sudden6** [KDE-mac/homebrew-kde#285]
In our CI `kf5-sonnet` suddenly fails to build, see https://travis-ci.org/qTox/qTox/jobs/506472812#L7210 for the relevant log output.

Nothing was changed on our side, did any dependencies for `kf5-sonnet` change?

**Comment by yurikoles** [comment]
Its new release of frameworks, 5.56

**Comment by yurikoles** [comment]
Builds fine on my machine

**Comment by sudden6** [comment]
I have restarted the build to check if this is only transient, but still no luck.

Could it be a problem that we use the `xcode9.2` image with `macOS 10.12` which is a bit old?

**Comment by yurikoles** [comment]
Maybe, I'm not sure. I run Mojave beta with stable Xcode.

**Comment by yurikoles** [comment]
Could run `brew gist-logs kf5-sonnet` and post a link here. Travis is very hard to navigate.

**Comment by sudden6** [comment]
I'll start a CI run with this command soon, meanwhile I copied the relevant log here: https://gist.github.com/sudden6/0479c4879bf398b27029d99aefb5911e

**Comment by sudden6** [comment]
I ran the command, but it seems to produce no output?

**Comment by yurikoles** [comment]
Duplicates #282

**Comment by yurikoles** [comment]
Sorry, messed up with tickets.

**Comment by scorpio810** [comment]
Hi, I have the same problem with  frameworks 5.56 : 
```
t/5.12.1/lib -framework QtSvg -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework QtPrintSupport -L/usr/local/Cellar/kf5-kwidgetsaddons/5.56.0_1/lib -lKF5WidgetsAddons -framework QtNetwork -framework QtXml -framework QtSql -framework QtConcurrent -L/usr/local/Cellar/kf5-kcoreaddons/5.56.0_1/lib -lKF5CoreAddons -framework OpenGL -framework AGL   
Undefined symbols for architecture x86_64:
  "KColorButton::setColor(QColor const&)", referenced from:
      ConductorPropertiesWidget::setProperties(ConductorProperties const&) in conductorpropertieswidget.o
      ShapeGraphicsItemPropertiesWidget::updateUi() in shapegraphicsitempropertieswidget.o
      DynamicTextFieldEditor::updateForm() in dynamictextfieldeditor.o
      TextEditor::updateForm() in texteditor.o
  "KColorButton::KColorButton(QWidget*)", referenced from:
      Ui_ConductorPropertiesWidget::setupUi(QWidget*) in conductorpropertieswidget.o
      Ui_ShapeGraphicsItemPropertiesWidget::setupUi(QWidget*) in shapegraphicsitempropertieswidget.o
      Ui_DynamicTextFieldEditor::setupUi(QWidget*) in dynamictextfieldeditor.o
      Ui_TextEditor::setupUi(QWidget*) in texteditor.o
  "KAutoSaveFile::allStaleFiles(QString const&)", referenced from:
      QETApp::checkBackupFiles() in qetapp.o
  "KAutoSaveFile::KAutoSaveFile(QUrl const&, QObject*)", referenced from:
      QETProject::setFilePath(QString const&) in qetproject.o
  "KColorButton::color() const", referenced from:
      ConductorPropertiesWidget::properties() const in conductorpropertieswidget.o
      ShapeGraphicsItemPropertiesWidget::associatedUndo() const in shapegraphicsitempropertieswidget.o
  "KAutoSaveFile::managedFile() const", referenced from:
      QETApp::checkBackupFiles() in qetapp.o
      QETDiagramEditor::openBackupFiles(QList<KAutoSaveFile*>) in qetdiagrameditor.o
      QETProject::QETProject(KAutoSaveFile*, QObject*) in qetproject.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [qelectrotech.app/Contents/MacOS/qelectrotech] Error 1
```
Thanks

**Comment by scorpio810** [comment]
It's Builded fine last week on 5.55 Framework but since last " brew upgrade" I have linker error at the end of compile : 
I copy my libs  like  cp /usr/local/opt/kf5-kwidgetsaddons/mkspecs/modules/qt_KWidgetsAddons.pri  /usr/local/opt/qt5/mkspecs/modules/
etc.
Perhaps isn't the good way ?
full log : 
https://download.tuxfamily.org/qet/log/build-macos.txt

**Comment by yurikoles** [comment]
@sudden6
It must produce a link to uploaded gist.

@scorpio810
Same question for you, please provide output of `brew gist-logs kf5-sonnet`.

**Comment by yurikoles** [comment]
I hope to fill an issue upstream soon.

**Comment by yurikoles** [comment]
CC: @krrk, @haraldF

**Comment by sudden6** [comment]
@yurikoles It seems the command errors out:
```
Error: A newer Command Line Tools release is available.
Update them from Software Update in the App Store.
```

However, I can't update the Command Line Tools on TravisCI.

**Comment by scorpio810** [comment]
Fixed now for me.
I use  args << "-DKDE_INSTALL_QTPLUGINDIR=lib/qt5/plugins" instead off args << "-DKDE_INSTALL_PLUGINDIR=lib/qt5/plugins" in kf5-kwidgetsaddons.rb, kf5-kcoreaddons.rb Formula.
Like kf5-kross: fix qt plugin path commit.

**Comment by sl1pkn07** [comment]
try now

**Comment by sl1pkn07** [comment]
is strange, but none of the packages use internally KDE_INSTALL_PLUGINDIR or KDE_INSTALL_QTPLUGINDIR. maybe previous failed installation?

**Comment by scorpio810** [comment]
Strange, but work, thanks.
brew upgrade
ln -sfv "$(brew --prefix)/share/kf5" "$HOME/Library/Application Support"
cp /usr/local/opt/kf5-kwidgetsaddons/mkspecs/modules/qt_KWidgetsAddons.pri /usr/local/opt/qt5/mkspecs/modules/

cp /usr/local/opt/kf5-kcoreaddons/mkspecs/modules/qt_KCoreAddons.pri  /usr/local/opt/qt5/mkspecs/modules/


[ful log](https://download.tuxfamily.org/qet/log/brew_upgrade.txt)

**Comment by sudden6** [comment]
The build still fails for me, log: https://gist.github.com/sudden6/bba305ae876d0f98d231b2f06b9b0019

**Comment by sl1pkn07** [comment]
please perform `brew doctor`  and `brew cleanup` and try again

only for discard things

greetings

**Comment by sudden6** [comment]
@sl1pkn07 these commands didn't help, I guess they don't have a lot to clean on TraviCI since it's a fresh VM.
